# Multi-stage Dockerfile for Next.js 15 app targeting ARM64 (Raspberry Pi 5)
# Uses bun for faster builds and smaller runtime

# ----- Builder -----
FROM --platform=$BUILDPLATFORM oven/bun:1-debian AS builder

ENV NODE_ENV=development \
    NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

# Install deps first (better layer caching)
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Copy the rest of the source
COPY . .

# Build Next.js (standalone output makes the runtime image smaller)
ENV NODE_ENV=production
RUN bun run build

# ----- Runner -----
FROM --platform=linux/arm64 node:20-bookworm-slim AS runner

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Create non-root user (use the pre-existing node user)
WORKDIR /app

# Copy the standalone build and static assets from builder
# Next.js standalone includes the minimal node_modules needed at runtime
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Expose port
EXPOSE 3000

# Drop privileges
USER node

# Start the Next.js server generated by standalone build
CMD ["node", "server.js"]
