# Multi-stage Dockerfile for Next.js 15 app targeting ARM64 (Raspberry Pi 5)
# Uses Debian slim for maximum compatibility with native binaries

# ----- Builder -----
FROM --platform=$BUILDPLATFORM node:20-bookworm-slim AS builder

ENV NODE_ENV=development \
    NEXT_TELEMETRY_DISABLED=1

# Install system deps (git for some installs, and libc locales just in case)
RUN apt-get update && apt-get install -y --no-install-recommends \
    git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install deps first (better layer caching)
# If you have a lockfile, copy it instead and prefer `npm ci`
COPY package.json ./
# If package-lock.json existed we would do: COPY package*.json ./
# and run: npm ci
RUN npm install

# Copy the rest of the source
COPY . .

# Build Next.js (standalone output makes the runtime image smaller)
ENV NODE_ENV=production
RUN npm run build

# ----- Runner -----
FROM --platform=linux/arm64 node:20-bookworm-slim AS runner

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Create non-root user (use the pre-existing node user)
WORKDIR /app

# Copy the standalone build and static assets from builder
# Next.js standalone includes the minimal node_modules needed at runtime
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Expose port
EXPOSE 3000

# Drop privileges
USER node

# Start the Next.js server generated by standalone build
CMD ["node", "server.js"]
